// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	GetTask(ctx context.Context, id int64) (Task, error)
	ListTasks(ctx context.Context) ([]Task, error)
}

var _ Querier = (*Queries)(nil)
